import sqlite3
conexao = sqlite3.connect("oficina.db")
cursor = conexao.cursor()
nome = input("Digite o nome do cliente: ")
telefone = input("Digite o telefone do cliente: ")
endereco = input("Digite o endereço do cliente: ")
cursor.execute("""
INSERT INTO clientes (nome, telefone, endereco)
VALUES (?, ?, ?)
""", (nome, telefone, endereco))
cursor.execute("SELECT * FROM clientes")
print(cursor.fetchall())
placa = input("Digite a placa do seu veículo: ")
ano = int(input("Digite o ano do seu veículo: "))
modelo = input("Digite o modelo do seu veículo: ")
cliente_id = int(input("Digite o número do seu cadastro: "))
cursor.execute("""
INSERT INTO veiculos (placa, modelo, ano, cliente_id)
VALUES (?, ?, ?, ?)
""", (placa, modelo, ano, cliente_id))
cursor.execute("SELECT * FROM veiculos")
print(cursor.fetchall())
descricao = input("Descreva o serviço realizado: ")
valor = float(input("Valor total do serviço: "))
data = input("Digite a data de entrada: ")
quilometros = int(input("Digite os km do carro: "))
veiculo_id = int(input("Digite o id do veículo: "))
cursor.execute("""
INSERT INTO servicos (descricao, valor, data, quilometros, veiculo_id)
VALUES (?, ?, ?, ?, ?)
""", (descricao, valor, data, quilometros, veiculo_id))
cursor.execute("SELECT * FROM servicos")
print(cursor.fetchall())

nome = input("Nome da peça: ")
quantidade = int(input("Quantidade no estoque: "))
valor = float(input("Valor da peça: "))
fornecedor = input("Fornecedor: ")
cursor.execute("""
INSERT INTO pecas (nome, quantidade, valor, fornecedor)
VALUES (?, ?, ?, ?)
""", (nome, quantidade, valor, fornecedor))
cursor.execute("SELECT * FROM pecas")
print(cursor.fetchall())
data = input("Data do orçamento: ")
valor_total = float(input("Valor total: "))
veiculo_id = int(input("ID do veículo: "))
cursor.execute("""
INSERT INTO orcamentos (data, valor_total, veiculo_id)
VALUES (?, ?, ?)
""", (data, valor_total, veiculo_id))
cursor.execute("SELECT * FROM orcamentos")
print(cursor.fetchall())

conexao.commit()
conexao.close()